# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  concurrency: 4
  timeout: 5m
  go: '1.24'

formatters:
  enable:
    - gci
    - gofmt
    - goimports

output:
  formats:
    json:
      path: stdout
      colors: true
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
    checkstyle:
      path: report.xml
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - contextcheck
    - decorder
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gochecksumtype
    #- gocognit
    - goconst
    #- gocyclo
    #- godox
    - goheader
    - goprintffuncname
    #- gosec
    - govet
    #- ireturn
    - loggercheck
    - promlinter
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    #- testpackage
    - unparam
    - unused
    - wastedassign
    - whitespace

severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info