apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pg.name }}-sec
data:
  postgres_database: {{ .Values.pg.credentials.database | b64enc }}
  postgres_user: {{ .Values.pg.credentials.username | b64enc }}
  postgres_password: {{ .Values.pg.credentials.password | b64enc }}
---
# TODO: set it up to allow running from values file
#{{- if and (.Values.api.pullSecret) (not .Values.api.distributedPullSecret) }}
#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ .Values.api.pullSecret }}
#type: kubernetes.io/dockerconfigjson
#data:
#  .dockerconfigjson: {{ .Values.api.dockerConfigSecret | b64enc }}
#{{- end }}
