apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pg.name }}
spec:
  selector:
    app: postgres
  ports:
  - port: {{ .Values.pg.containerPort }}
    targetPort: {{ .Values.pg.containerPort }}
    protocol: TCP