---
{{- if and (.Values.api.pullSecret) (.Values.api.distributedPullSecret) }}
apiVersion: secdist.etzba.com/v1
kind: Distribution
metadata:
  labels:
    app.kubernetes.io/name: secret-distributor
  name: {{ .Values.api.pullSecret }}-distribution
spec:
  secretName: {{ .Values.api.pullSecret }}
{{- end }}
