on:
  push:
    # Pattern matched against refs/tags
    tags:  
      - 'v[12].[0-9]+.[0-9]+'
      - 'v[12].[0-9]+.[0-9]-rc[0-9]+'

jobs:
  test:
    name: Run unit tests on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test

  go-build:
    name: Build app on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build app
        env:
          CGO_ENABLED: 0 
          GOOS: linux 
          GOARCH: amd64
        run: |
          go build -a -o app main.go

  lint:
    name: Run golangci linter on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

  build-container:
    name: Build and push container image
    needs: [test, go-build] 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "tag=$(${GITHUB_REF} | awk -F "/" '{print $3}')" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.extract_tag.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.extract_tag.outputs.tag }}
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: etzba
          password: ${{ secrets.ghcrToken }}
      - name: Publish container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ steps.extract_tag.outputs.tag }}
            org.opencontainers.image.version=${{ env.VERSION }}
      - name: Publish container image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ steps.extract_tag.outputs.tag }}
            org.opencontainers.image.version=${{ env.VERSION }}
      - name: sign container image
        run: |
            echo '${{ secrets.COSIGN_KEY }}' > cosign.key
            cosign sign --key cosign.key ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
        shell: bash
        env:
          COSIGN_KEY: |
            ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ""
      - name: Check images
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          docker pull ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          echo '${{ secrets.COSIGN_PUBLIC_KEY }}' > cosign.pub
          cosign verify --key cosign.pub ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: etzba
          password: ${{ secrets.dockerHubToken }}
      - name: Publish container image to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ steps.extract_tag.outputs.tag }}
            org.opencontainers.image.version=${{ env.VERSION }}
      - name: sign container image
        run: |
            echo '${{ secrets.COSIGN_KEY }}' > cosign.key
            cosign sign --key cosign.key docker.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
        shell: bash
        env:
          COSIGN_KEY: |
            ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ""
      - name: Check images
        run: |
          docker buildx imagetools inspect docker.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          docker pull docker.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
          echo '${{ secrets.COSIGN_PUBLIC_KEY }}' > cosign.pub
          cosign verify --key cosign.pub docker.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
